# Generated by Django 4.2.28 on 2026-02-07 15:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('ogretmen', 'Öğretmen')], default='ogretmen', max_length=10)),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('adres', models.TextField(blank=True)),
                ('profil_resmi', models.ImageField(blank=True, null=True, upload_to='profil_resimleri/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'kullanicilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DersProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(max_length=100)),
                ('gun', models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma')])),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('aktif', models.BooleanField(default=True)),
                ('ogretmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_programlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ders Programı',
                'verbose_name_plural': 'Ders Programları',
                'db_table': 'ders_programlari',
                'ordering': ['gun', 'baslangic_saati'],
            },
        ),
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True)),
                ('aciklama', models.TextField(blank=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sınıf',
                'verbose_name_plural': 'Sınıflar',
                'db_table': 'siniflar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Yoklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('ders_basligi', models.CharField(max_length=200)),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_zamani', models.DateTimeField(auto_now=True)),
                ('ders_programi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoklamalar', to='core.dersprogrami')),
                ('ogretmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoklamalar', to=settings.AUTH_USER_MODEL)),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoklamalar', to='core.sinif')),
            ],
            options={
                'verbose_name': 'Yoklama',
                'verbose_name_plural': 'Yoklamalar',
                'db_table': 'yoklamalar',
                'ordering': ['-tarih', '-olusturma_zamani'],
                'unique_together': {('ders_programi', 'tarih')},
            },
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('tc_kimlik', models.CharField(max_length=11, unique=True)),
                ('dogum_tarihi', models.DateField()),
                ('cinsiyet', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kız')], max_length=1)),
                ('veli_adi', models.CharField(max_length=100)),
                ('veli_telefon', models.CharField(max_length=15)),
                ('adres', models.TextField(blank=True)),
                ('profil_resmi', models.ImageField(blank=True, null=True, upload_to='ogrenci_resimleri/')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aktif', models.BooleanField(default=True)),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenciler', to='core.sinif')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'db_table': 'ogrenciler',
                'ordering': ['ad', 'soyad'],
            },
        ),
        migrations.AddField(
            model_name='dersprogrami',
            name='sinif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_programlari', to='core.sinif'),
        ),
        migrations.CreateModel(
            name='YoklamaDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok'), ('izinli', 'İzinli'), ('gec', 'Geç Kaldı')], default='var', max_length=10)),
                ('not_durumu', models.TextField(blank=True)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoklama_detaylari', to='core.ogrenci')),
                ('yoklama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='core.yoklama')),
            ],
            options={
                'verbose_name': 'Yoklama Detayı',
                'verbose_name_plural': 'Yoklama Detayları',
                'db_table': 'yoklama_detaylari',
                'unique_together': {('yoklama', 'ogrenci')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dersprogrami',
            unique_together={('ogretmen', 'sinif', 'gun', 'baslangic_saati')},
        ),
    ]
