# Generated by Django 4.2.28 on 2026-02-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yoklama',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dersprogrami',
            name='gun',
            field=models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (7, 'Pazar')]),
        ),
    ]
