# Generated by Django 4.2.27 on 2026-02-17 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yoklama',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='profil_resmi',
        ),
        migrations.AddField(
            model_name='dersprogrami',
            name='derslik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dersprogrami',
            name='gun',
            field=models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')]),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='adres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kız')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='veli_adi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='veli_telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='OgrenciNotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('genel', 'Genel Not'), ('tatil', 'Tatil/İzin'), ('odeme', 'Ödeme'), ('disiplin', 'Disiplin'), ('saglik', 'Sağlık'), ('basari', 'Başarı/Ödül')], default='genel', max_length=20)),
                ('baslik', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('tarih', models.DateField()),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_zamani', models.DateTimeField(auto_now=True)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='core.ogrenci')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğrenci Notu',
                'verbose_name_plural': 'Öğrenci Notları',
                'db_table': 'ogrenci_notlari',
                'ordering': ['-tarih', '-olusturma_zamani'],
            },
        ),
    ]
